# Generated by Django 5.0.7 on 2025-04-29 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Enter a category name (e.g., Salary, Food, Transportation)",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "user", "category_type")},
        ),
    ]
