# Generated by Django 5.0.7 on 2025-04-29 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_category_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#4361ee", max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("user", "name", "category_type")},
        ),
    ]
